baseURL = "http://example.org/"
theme = "wiki"

defaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1

    title = "Mahjogn Wiki"
    description = "Mahjogn Wiki"
    contentDir = "content/english"
  [languages.ru]
    languageName = "Русский"
    weight = 2

    title = "Маджонг wiki"
    description = "Маджонг wiki"
    contentDir = "content/russian"
