version: '2'

volumes:
  local_mariadb_data: {}

services:

  database:
    image: mariadb:10.5.4
    env_file:
      - ./.env
    volumes:
      - local_mariadb_data:/var/lib/mysql
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'

  mahjong_wiki:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: custom_mediawiki
    links:
      - database
    volumes:
      - ./images:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
    restart: always
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    ports:
      - '6102:80'