version: '3'

services:
  build:
    image: klakegg/hugo:0.73.0
    volumes:
      - ".:/src"
    environment:
      - HUGO_DESTINATION=/public
  server:
    image: klakegg/hugo:0.73.0
    command: server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
  format-md:
    image: tmknom/prettier:2.0.5
    command: --parser=markdown --write '/src/content/**/*.md' --print-width 100 --prose-wrap always
    volumes:
      - ".:/src"
  lint-md:
    image: tmknom/prettier:2.0.5
    command: --parser=markdown '/src/content/**/*.md' --print-width 100 --prose-wrap always --check
    volumes:
      - ".:/src"