name: Wiki
on:
  push:
    paths:
      - 'content/**'
jobs:
  run:
    name: Run markdown linter
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Lint markdown
        run: make lint-md